import { StyleSheet } from 'react-native';
import type { useAppTheme } from '@/providers/AppThemeProvider';

export function createHomeStyles(
  colors: ReturnType<typeof useAppTheme>['colors'],
  fonts: ReturnType<typeof useAppTheme>['fonts']
) {
  return StyleSheet.create({
    content: {
      paddingTop: 0,
      paddingBottom: 44,
    },
    heroCard: {
      position: 'relative',
      overflow: 'hidden',
      marginTop: -6,
      paddingBottom: 22,
    },
    heroBackdropBand: {
      position: 'absolute',
      borderRadius: 32,
      transform: [{ rotate: '-14deg' }],
    },
    heroBackdropBandPrimary: {
      width: 240,
      height: 70,
      backgroundColor: colors.accentSoft,
      top: 28,
      right: -46,
    },
    heroBackdropBandSecondary: {
      width: 180,
      height: 54,
      backgroundColor: colors.accentSecondarySoft,
      bottom: 54,
      left: -36,
    },
    heroBackdropGrid: {
      position: 'absolute',
      top: 22,
      right: 20,
      width: 108,
      height: 108,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      opacity: 0.24,
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 18,
    },
    heroCopy: {
      flex: 1,
    },
    heroHeading: {
      color: colors.text,
      fontFamily: fonts.display,
      fontSize: 32,
      lineHeight: 36,
      letterSpacing: -0.9,
      marginTop: 8,
    },
    heroSubheading: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
      marginTop: 10,
      maxWidth: 520,
    },
    goalSettingsButton: {
      minWidth: 84,
      height: 42,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingHorizontal: 12,
    },
    goalSettingsText: {
      color: colors.text,
      fontFamily: fonts.label,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    heroBody: {
      marginTop: 24,
      gap: 18,
    },
    lanesCard: {
      backgroundColor: 'rgba(255,255,255,0.03)',
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
      gap: 18,
    },
    lanesHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 14,
    },
    lanesHeaderCopy: {
      flex: 1,
    },
    lanesEyebrow: {
      color: colors.textMuted,
      fontFamily: fonts.label,
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    lanesTitle: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 18,
      lineHeight: 22,
      letterSpacing: -0.3,
      marginTop: 8,
    },
    lanesSubtitle: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 13,
      lineHeight: 19,
      marginTop: 8,
    },
    lanesScore: {
      minWidth: 74,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 18,
      backgroundColor: colors.card3,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    lanesScoreLabel: {
      color: colors.textMuted,
      fontFamily: fonts.label,
      fontSize: 10,
      lineHeight: 12,
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    lanesScoreValue: {
      color: colors.text,
      fontFamily: fonts.display,
      fontSize: 24,
      lineHeight: 30,
      letterSpacing: -0.8,
      marginTop: 4,
    },
    ringsLayout: {
      gap: 18,
      alignItems: 'center',
    },
    ringsVisualWrap: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringCenter: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringCenterValue: {
      color: colors.text,
      fontFamily: fonts.display,
      fontSize: 28,
      lineHeight: 32,
      letterSpacing: -0.8,
    },
    ringCenterLabel: {
      color: colors.textMuted,
      fontFamily: fonts.label,
      fontSize: 10,
      lineHeight: 12,
      letterSpacing: 0.7,
      textTransform: 'uppercase',
      marginTop: 6,
    },
    ringsLegend: {
      width: '100%',
      gap: 12,
    },
    ringsLegendRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    ringsLegendDot: {
      width: 10,
      height: 10,
      borderRadius: 999,
      marginTop: 4,
    },
    ringsLegendCopy: {
      flex: 1,
    },
    ringsLegendLabelRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 10,
    },
    ringsLegendLabel: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 14,
      lineHeight: 18,
    },
    ringsLegendStatus: {
      fontSize: 10,
      lineHeight: 12,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    ringsLegendSummary: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 3,
    },
    heroSide: {
      gap: 12,
    },
    heroMetricCard: {
      minHeight: 96,
      justifyContent: 'space-between',
    },
    heroMetricLabel: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 16,
    },
    heroMetricValue: {
      color: colors.text,
      fontFamily: fonts.display,
      fontSize: 24,
      lineHeight: 28,
      letterSpacing: -0.7,
      marginTop: 6,
    },
    heroMetricHint: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 8,
    },
    heroFooterRow: {
      flexDirection: 'row',
      gap: 10,
    },
    heroChip: {
      flex: 1,
      minHeight: 42,
      justifyContent: 'center',
      gap: 8,
    },
    heroChipText: {
      flex: 1,
      color: colors.text,
    },
    sectionHeader: {
      marginTop: 28,
      marginBottom: 14,
      gap: 4,
    },
    sectionTitle: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 24,
      lineHeight: 28,
      letterSpacing: -0.5,
    },
    sectionSubtitle: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
    },
    actionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    actionTile: {
      width: '48%',
      minHeight: 172,
      justifyContent: 'space-between',
    },
    actionIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
    },
    actionTitle: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 17,
      lineHeight: 21,
      letterSpacing: -0.3,
    },
    actionSubtitle: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 13,
      lineHeight: 19,
      marginTop: 8,
    },
    actionFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 16,
    },
    actionFooterText: {
      color: colors.text,
      fontFamily: fonts.label,
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    completionCard: {
      width: '48%',
      minHeight: 174,
      justifyContent: 'space-between',
    },
    completionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    completionIcon: {
      width: 40,
      height: 40,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardTitle: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 18,
      lineHeight: 22,
      letterSpacing: -0.3,
      marginTop: 6,
    },
    completionStatsRow: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 18,
    },
    completionStat: {
      flex: 1,
      backgroundColor: colors.card3,
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    completionStatLabel: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 16,
    },
    completionStatValue: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 15,
      lineHeight: 20,
      marginTop: 8,
    },
    completionFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 20,
    },
    completionFooterText: {
      color: colors.textMuted,
      fontFamily: fonts.label,
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    nutritionCard: {
      position: 'relative',
      overflow: 'hidden',
    },
    nutritionBackdropFrame: {
      position: 'absolute',
      top: 18,
      right: 18,
      width: 132,
      height: 84,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'rgba(255,255,255,0.02)',
    },
    nutritionBackdropStripe: {
      position: 'absolute',
      top: 42,
      right: -28,
      width: 160,
      height: 18,
      borderRadius: 999,
      backgroundColor: colors.accentSoft,
      opacity: 0.28,
      transform: [{ rotate: '-12deg' }],
    },
    nutritionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    summaryChip: {
      gap: 6,
      minHeight: 34,
      justifyContent: 'center',
    },
    summaryChipText: {
      color: colors.highlight1,
    },
    nutritionRow: {
      marginTop: 20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 18,
    },
    calorieDialBlock: {
      width: '42%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.03)',
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 18,
      paddingHorizontal: 14,
    },
    donutWrap: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    donutCenter: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
      maxWidth: 110,
    },
    donutValue: {
      color: colors.text,
      fontFamily: fonts.display,
      fontSize: 24,
      lineHeight: 28,
      letterSpacing: -0.7,
    },
    donutLabel: {
      color: colors.textMuted,
      fontFamily: fonts.label,
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginTop: 4,
    },
    donutSubtext: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 11,
      lineHeight: 16,
      textAlign: 'center',
      marginTop: 6,
    },
    macroPanel: {
      flex: 1,
      minWidth: 0,
      gap: 16,
      justifyContent: 'center',
    },
    macroRow: {
      gap: 8,
    },
    macroRowTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    macroLabel: {
      color: colors.text,
      fontFamily: fonts.heading,
      fontSize: 14,
      lineHeight: 18,
    },
    macroValue: {
      color: colors.textMuted,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 16,
    },
    macroTrack: {
      height: 9,
      borderRadius: 999,
      backgroundColor: colors.card3,
      overflow: 'hidden',
    },
    macroFill: {
      height: '100%',
      borderRadius: 999,
      minWidth: 0,
    },
    nutritionActions: {
      marginTop: 22,
    },
    nutritionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    nutritionButtonFull: {
      width: '100%',
    },
  });
}

export type HomeStyles = ReturnType<typeof createHomeStyles>;
